mristin/opinionated-commit-message

- package.json
- src/mostFrequentEnglishVerbs.ts
This extends the list of most frequent verbs with "rewrite" and
"refactor", a widely used verbs in the context of programming.
> Add "rewrite" and "refactor" to verbs

- dist/index.js
- package.json
This commit marks the release of version 1.0.1.
> Release 1.0.1

- dist/index.js
- package.json
This commit marks the release of version 1.0.3.
> Release 1.0.3

- src/mostFrequentEnglishVerbs.ts
This adds "upgrade" to the list of acceptable verbs in imperative mood.
> Add "upgrade"

- dist/index.js
- package.json
This commit marks the release of version 1.0.4.
> Release 1.0.4

- dist/index.js
- package.json
This commit marks the release of version 1.0.5.
> Release 1.0.5

- src/mostFrequentEnglishVerbs.ts
This adds "rename" to the list of accepted verbs.
> Add "rename"

- dist/index.js
- package.json
This commit marks the release of version 1.0.6.
> Release 1.0.6

- src/mostFrequentEnglishVerbs.ts
This adds "revert" to the list of accepted verbs.
> Add "revert"

- dist/index.js
- package.json
This commit marks the release of version 1.0.7.
> Release 1.0.7

- src/mostFrequentEnglishVerbs.ts
This adds "correct" to the list of accepted verbs.
> Add "correct"

- src/mostFrequentEnglishVerbs.ts
This adds "invalidate" to the list of accepted verbs.
> Add "invalidate"

- dist/index.js
- package.json
This commit marks the release of version 1.0.8.
> Release 1.0.8

- src/mostFrequentEnglishVerbs.ts
This adds "clarify" to the list of verbs in imperative mood.
> Add "clarify"

- .github/workflows/build-and-test.yml
- README.md
- action.yml
- dist/index.js
- src/__tests__/inspection.test.ts
- src/__tests__/main.test.ts
- src/inspection.ts
- src/mainImpl.ts
This introduces an input variable to the action to allow for
whitelisting additional verbs in imperative mood.
> Allow additional verbs

- README.md
- package.json
This commit marks the pre-release 2.0.0-pre1.
> Release 2.0.0-pre1

- src/mostFrequentEnglishVerbs.ts
This adds verbs sampled from the commit messages of the repository
github.com/admin-shell-io/aasx-package-explorer living on the
development branch `V20DataModel`.
> Add verbs from V20DataModel

- dist/index.js
- package.json
- src/mostFrequentEnglishVerbs.ts
This commit marks the pre-release at version 2.0.0-pre2.
> Release 2.0.0-pre2

- dist/index.js
- package.json
This commit marks the pre-release at version 2.0.0-pre3.
> Release 2.0.0-pre3

- local/powershell/OpinionatedCommitMessage.Tests.ps1
- local/powershell/OpinionatedCommitMessage.ps1
- local/powershell/OpinionatedCommitMessage.ps1.template
I forgot to translate the sign-off enforcement in the pull request #74.
> Implement sign-off enforcement in Powershell

- README.md
- package.json
> Release 2.3.0

- src/__tests__/main.test.ts
Currently, the state of the core mock is leaking between the tests since
we mocked the functions using non-idiomatic replacement with plain
functions instead of using jest function mocks.
This patch introduces proper mock functions and resets the mocks between
each test.
> Make tests of main independent and idiomatic

- dist/index.js
- src/mostFrequentEnglishVerbs.ts
Examples:
* Group functions by their domain
* Group classes by their target
> Add "group" to the list of verbs

- src/mostFrequentEnglishVerbs.ts
- Add "transform" to the list of verbs
> Add "transform" to the list of verbs

- README.md
- package.json
* Change `ncc` from zeit to vercel (#118)
* Add "transform" to the list of verbs (#116)
* Add "group" to the list of verbs (#106)
* Add expose to the list of verbs (#104)
> Release 3.0.1

- src/mostFrequentEnglishVerbs.ts
This PR adds "parse" to the list of verbs.
> Add "parse" to the list of verbs

- action.yml
- dist/index.js
- package-lock.json
- package.json
- tsconfig.json
> Upgrade action and packages to Node 20

- README.md
- package.json
* Upgrade action and packages to Node 20 (#126)
* Add support for ignored patterns (#124)
* Check commits instead of PR text for pull requests (#122)
* Refactor inputs as named parameters (#121)
* Update all dependencies (#120)
> Release 3.1.0

- src/mostFrequentEnglishVerbs.ts
I was mashing two services together and my commit was rejected :)
> Add 'mash' to verbs list
