mristin/opinionated-commit-message

package.json
src/mostFrequentEnglishVerbs.ts

This extends the list of acceptable verbs with two verbs ("reorganise"
and "restrcture") which are commonly used in the context of programming.

Add "reorganise" and "restructure" to verbs

---

dist/index.js

The `dist/` was forgotten in the previous commit.

Add 1.0.2 dist

---

package.json
src/__tests__/inspection.test.ts
src/inspection.ts

Github and similar services often add a (hash) code referring to the
pull request in the commit message *after* the squash & merge.
This change adds tolerance for the code so that the commit messages also
pass the test *after* the merge.

Tolerate hash code in subject

---

package.json
src/mostFrequentEnglishVerbs.ts

This adds the abovementioned verbs to the list of acceptable verbs in
imperative mood.

Add "unify", "reword" and "rephrase"

---

src/mostFrequentEnglishVerbs.ts

This adds verbs `reformat` and `update` to the list after fixing the 
lines of aasx-package-explorer to 120 characters.

Add `reformat` and `update` verbs

---

src/mostFrequentEnglishVerbs.ts

This patch adds even more verbs that are often used in commit messages
to the list of exceptions.

Add more exceptions to the verb list

---

dist/index.js
src/commitMessages.ts

This uses intermediate variables to make `commitMessages` a bit easier
to read.

Simplify commitMessages with variables

---

dist/index.js
src/mainImpl.ts

There was no information shown to user if the message was OK which
is sometimes misleading and prevents users from verifying the
behvaior of the action.
This displays a message to the user both on invalid and valid messages.

Inform user about OK messages

---

src/__tests__/inspection.test.ts

This adds a test case for inspection of messages of exactly 72
characters in length.

Test messages of exactly 72 characters

---

README.md
dist/index.js

This differentiates the events in the Readme and explains what is
actually checked in each of the events, respectively.
Additionally, we explain that it is a known issue that the commits
of the pull request are not validated.

Clarify push *versus* pull request in Readme

---

package.json

This gives a shortcut to running eslint in fix mode.

Introduce npm script `fix`

---

dist/index.js
src/__tests__/inspection.test.ts
src/inspection.ts

The error messages turned out to be too cryptic. In particular, it
was quite difficult to debug why a seemingly correct body line of
72 characters surpassed the limit.
This adds the offending lines as JSON strings to the error messages.
In particular, it should help trace the cause of the issue #26.

Make error mesages more informative

---

dist/index.js
src/__tests__/inspection.test.ts
src/inspection.ts

Merge commit messages are automatically generated by Git.
There is little point to rewrite them by the developer, so we ignore
them although they do not conform to the rules.

Ignore merge messages

---

dist/index.js
src/__tests__/inspection.test.ts
src/__tests__/main.test.ts
src/inspection.ts
src/mostFrequentEnglishVerbs.ts

It is too strict to require the body to start with a capitalied word.
Oftentimes, the body lists the changes as bullet points or uses
a similar styling.
For an example, this fixes issue #29.

Relax checks on body messages

---

dist/index.js
src/mostFrequentEnglishVerbs.ts

This adds "wrap", "unwrap" and "rewrap" to the list of accepted
verbs in imperative mood.

Add "wrap", "unwrap" and "rewrap"

---

src/mostFrequentEnglishVerbs.ts

This patch adds the verbse "delete" and "erase" to the list of
accepted verbs in imperative mood.

Add "delete" and "erase"

---

src/__tests__/inspection.test.ts
src/inspection.ts

Windows system add carriage return to the end of lines which triggered
a lot of false positives. This patch ignores the final carriage return
at the end of line.

Ignore carriage return

---

.github/workflows/build-and-test.yml
README.md
src/__tests__/input.test.ts
src/__tests__/main.test.ts
src/additional-verbs.txt
src/input.ts
src/mainImpl.ts

While the workflow input `additional-verbs` allows you to whitelist
additional verbs in imperative mood, it can also make the workflow file
barely readable if the list becomes long.
This enhancement allows users to supply an extra file *via*
`path-to-additional-verbs` containing the additional verbs.

Add text file as input

---

action.yml

The input `path-to-additional-verbs` was mistakenly omitted from the
`action.yml` specification. This patch adds it to the specification.

Add `path-to-additional-verbs` to `action.yml`

---

README.md
local/powershell/OpinionatedCommitMessage.Tests.ps1
local/powershell/OpinionatedCommitMessage.ps1
local/powershell/OpinionatedCommitMessage.ps1.template
src/__tests__/inspection.test.ts
src/inspection.ts

This patch allows long URLs on separate lines or as link definitions
in the body. This is necessary so that the link functionality does not
break in the readers such as terminals and Github.
Fixes #59.

Allow URLs as separate lines and link definitions

---

dist/index.js

This is a post-fix for 2.2.1 release. `Dist` folder was not
checked in by mistake.

Fix missed `dist` in the release of 2.2.1

---

.eslintrc.json
dist/index.js
local/powershell/OpinionatedCommitMessage.Tests.ps1
local/powershell/OpinionatedCommitMessage.ps1
local/powershell/OpinionatedCommitMessage.ps1.template
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/__tests__/main.test.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts
src/mostFrequentEnglishVerbs.ts

In many teams, the wider team is not aware how the GitHub action has
been set up and merely sees the messages in their CI reports. These
users are ultimately lost and need further guidance on how to fix the
errors in their commit messages. In particular, sparse error messages
with no hints how to remedy the commit messages are almost useless
leaving the users utterly frustrated.
This change introduces very verbose error messages which include the
hints what can be done about the message. While the messages are now
quite long and seem cluttered, they are hopefully much more useful to
the inexperienced users.

Instruct how to remedy the issues

---

README.md

The Readme instructed the user to specify only
the major version, but that doesn't work any more.
Fixes #70 .

Put latest full version in the Readme

---

action.yml
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts

This patch adds a flag to enforce a sign-off of a commit. See [1] for
more information.
Fixes #73.
[1]: https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

Add sign-off enforcement

---

README.md

This patch documents the flag `enforce-sign-off` in the README.
The documentation was forgotten in haste.

Document `enforce-sign-off`

---

package-lock.json
package.json

Dependabot alerted us that the dependency `@actions/core` need to be
updated to a newer version.

Bump `@actions/core` to 1.2.6 for security

---

README.md
action.yml
dist/index.js
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/__tests__/main.test.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts

Some organizations prefer to use only a subject
line, usually referring to the pull request, as
it provides the full context for the change.
Other reasons for using a subject line-only
include incompatibility with automatic PR bots,
like Renovate. Besides this, most teams today use
some UI to read the PR's message body
(i.e., GitHub), so restricting what can be added
to a PR message can lead to a poor
user experience.
Signed-off-by: Marcos Passos <marcos@croct.com>

Allow skipping message body check

---

README.md
action.yml
dist/index.js
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts

The limit of 72 characters is great for strict terminal use and some
GUIs, but for teams that use only UIs such as GitHub Web it is an
unnecessary and harsh restriction.
This PR adds a `max-body-line-length` option to make this
configurable.
Signed-off-by: Luiz Ferraz <luiz.ferraz@croct.com>

Make max length of body lines configurable

---

src/mostFrequentEnglishVerbs.ts

Example:
- Expose `version` field of Foo
- Expose formatting functions

Add expose to the list of verbs

---

README.md

We specified only the major version in the readme which made the clients
fail. Instead, a full version needs to be indicated in the workflow
files.
Fixes #103.

Specify the exact version in Readme

---

dist/index.js
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/input.ts
src/mainImpl.ts

We change the arguments of `parseInputs` and the `Inputs` constructor
to receive an object with named arguments.
This allows for adding new properties without breaking existing tests
and more clarity on the inputs used on each test.

Refactor inputs as named parameters

---

.github/workflows/build-and-test.yml
README.md
action.yml
dist/index.js
package-lock.json
package.json
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/__tests__/main.test.ts
src/commitMessages.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts
src/mostFrequentEnglishVerbs.ts
src/represent.ts

Check commits instead of PR text for pull requests

---

action.yml
dist/index.js
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts

There was already logic to ignore merge commits,
but it was using a very restricted regular expression.
This PR:
- Improve the existing merge commit detection.
- Allow users to disable merge commit detection.
- Allow users to provide custom patterns to ignore
Related issues:
- Closes #110

Add support for ignored patterns

---

action.yml
dist/index.js
src/__tests__/input.test.ts
src/__tests__/inspection.test.ts
src/input.ts
src/inspection.ts
src/mainImpl.ts

When set an error will be emitted if the body does not contain enough characters. This is useful to require commit bodies with more information, like impact, motivation, approach, testing results, new behavior, *etc.*
Default: no minimum. Suggested: at least 150.
Fixes #136.

Add min-body-length option
